// pch.h: This is a precompiled header file.
// Files listed below are compiled only once, improving build performance for future builds.
// This also affects IntelliSense performance, including code completion and many code browsing features.
// However, files listed here are ALL re-compiled if any one of them is updated between builds.
// Do not add files here that you will be updating frequently as this negates the performance advantage.

#ifndef PCH_H
#define PCH_H

// add headers that you want to pre-compile here
#include "framework.h"

// lib
#include <SADXModLoader.h>

// objects
#include "objects/o_baneiwa.h"
#include "objects/o_bridgepole.h"
#include "objects/o_dome1.h"
#include "objects/o_dome2.h"
#include "objects/o_dome3.h"
#include "objects/o_flower0.h"
#include "objects/o_flower1.h"
#include "objects/o_grass1.h"
#include "objects/o_grass2.h"
#include "objects/o_grass3.h"
#include "objects/o_grass4.h"
#include "objects/o_green0.h"
#include "objects/o_ibou01.h"
#include "objects/o_ibou02.h"
#include "objects/o_ibou03.h"
#include "objects/o_idai1.h"
#include "objects/o_idai10.h"
#include "objects/o_idai2.h"
#include "objects/o_idai3.h"
#include "objects/o_idai4.h"
#include "objects/o_idai5.h"
#include "objects/o_idai6.h"
#include "objects/o_idai7.h"
#include "objects/o_idai8.h"
#include "objects/o_idai9.h"
#include "objects/o_ihah01.h"
#include "objects/o_ihah02.h"
#include "objects/o_ihah03.h"
#include "objects/o_ihah04.h"
#include "objects/o_ihah05.h"
#include "objects/o_ihah06.h"
#include "objects/o_ihas14.h"
#include "objects/o_ihas15.h"
#include "objects/o_ihas16.h"
#include "objects/o_ihas17.h"
#include "objects/o_ihas18.h"
#include "objects/o_ihas19.h"
#include "objects/o_ioiwa01.h"
#include "objects/o_ioiwa02.h"
#include "objects/o_ioiwa03.h"
#include "objects/o_iwab.h"
#include "objects/o_largerock1.h"
#include "objects/o_launch.h"
#include "objects/o_pinkf.h"
#include "objects/o_pole1.h"
#include "objects/o_pole2.h"
#include "objects/o_pot01.h"
#include "objects/o_pot02.h"
#include "objects/o_prop1.h"
#include "objects/o_prope1.h"
#include "objects/o_prope2.h"
#include "objects/o_prope3.h"
#include "objects/o_propea.h"
#include "objects/o_propeb.h"
#include "objects/o_propec.h"
#include "objects/o_raft.h"
#include "objects/o_raft2.h"
#include "objects/o_raft3.h"
#include "objects/o_rock1.h"
#include "objects/o_rock2.h"
#include "objects/o_rock3.h"
#include "objects/o_rock5.h"
#include "objects/o_sara_b1.h"
#include "objects/o_sara_b2.h"
#include "objects/o_sara_m1.h"
#include "objects/o_sara_m1.h"
#include "objects/o_sara_m2.h"
#include "objects/o_sara_s1.h"
#include "objects/o_sara_s2.h"
#include "objects/o_sbridge.h"
#include "objects/o_sirusi1.h"
#include "objects/o_sirusi10.h"
#include "objects/o_sirusi11.h"
#include "objects/o_sirusi12.h"
#include "objects/o_sirusi13.h"
#include "objects/o_sirusi2.h"
#include "objects/o_sirusi3.h"
#include "objects/o_sirusi4.h"
#include "objects/o_sirusi5.h"
#include "objects/o_sirusi6.h"
#include "objects/o_sirusi7.h"
#include "objects/o_sirusi8.h"
#include "objects/o_sirusi9.h"
#include "objects/o_takow.h"
#include "objects/o_tanpopo.h"
#include "objects/o_traft1.h"
#include "objects/o_traft2.h"
#include "objects/o_trampoline.h"
#include "objects/o_tspring.h"
#include "objects/o_windybolt.h"
#include "objects/o_windyelevator.h"
#include "objects/o_windygate.h"
#include "objects/o_windygear.h"
#include "objects/o_windyki1.h"
#include "objects/o_windyki2.h"
#include "objects/o_windykusa1.h"
#include "objects/o_yaji01.h"

#endif //PCH_H
